name: clean

on:
  workflow_dispatch:

jobs:
  cargo:
    name: cargo clean
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install rust
        uses: risc0/risc0/.github/actions/rustup@release-0.19

      - name: cargo clean
        run: cargo clean
